# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 356d881f02e7d31f21bbdd050c7d6657c1aebdbae0b8e36c83226a35c29eeb87364644644f52b3b26e1d4cb874e8f13abbe6717f23811d61af37859763f2428a

test:
  secret_key_base: 54af1cd6212a1dcf07967064c17e36e27cf3fd8c333f0828628151ab3ff932735cca47186c085b919f3686f5167876cd69fd7a6ffc1dab6fb504b2074347a156

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
